# 파이썬 리스트 구조 이해하기

## 1.1 리스트 구조 이해하기

### ex) 리스트 구조

In [2]:
l = [[1, 2, 3], [4, 5, 6]]
type(l)

list

리스트는 실제 원소의 객체를 저장하는 것이 아니라 이 객체의 레퍼런스를 관리한다.

In [4]:
l[0]

[1, 2, 3]

In [5]:
l[1]

[4, 5, 6]

In [6]:
for entry in enumerate(['A', 'B', 'C']):
    print(entry)

(0, 'A')
(1, 'B')
(2, 'C')


순서가 있는 자료형(list, set, tuple, dictionary, string)을 인자로 전달받았을 때, **인덱스와 값**을 포함하여 리턴

In [7]:
for i, a in enumerate(l):
    print(a)
    for j, b in enumerate(a):
        print(b)
        print(l[i][j])

[1, 2, 3]
1
1
2
2
3
3
[4, 5, 6]
4
4
5
5
6
6


## 1.2 다차원 배열의 구조 이해하기

### ex1)넘파이 배열 구조

In [8]:
import numpy as np
np.__version__

'2.2.6'

In [9]:
print(np.ndarray)

<class 'numpy.ndarray'>


In [10]:
np.ndarray.__name__

'ndarray'

In [11]:
for i in dir(np.ndarray):
    if not i.startswith("_"):
        if type(np.ndarray.__dict__[i]) != type(np.ndarray.var):
            print(i)

T
base
ctypes
data
device
dtype
flags
flat
imag
itemset
itemsize
mT
nbytes
ndim
newbyteorder
ptp
real
shape
size
strides


### ex2) 넘파이 배열 생성하기

In [12]:
l = [1, 2, 3, 4]

In [13]:
a = np.array(l)

In [14]:
a

array([1, 2, 3, 4])

In [15]:
type(a)

numpy.ndarray

In [16]:
t = (1, 2, 3, 4)

In [17]:
b = np.array(t)

In [18]:
type(b)

numpy.ndarray

In [19]:
a.data # data을 조회하면 메모리에 저장된 레퍼런스를 출력

In [20]:
a.data.obj # obj로 참조하면 배열의 값을 보여줌

array([1, 2, 3, 4])

In [21]:
type(a.data.obj)

numpy.ndarray

In [22]:
c = b # b 다차원 배열 별칭을 c로 지정

In [23]:
c.base is b.base

True

In [24]:
c[0] = 100

In [25]:
c

array([100,   2,   3,   4])

In [26]:
b

array([100,   2,   3,   4])

In [27]:
d = np.array(b)

In [28]:
d[0] = 99

In [29]:
d

array([99,  2,  3,  4])

In [30]:
b

array([100,   2,   3,   4])

In [31]:
e = np.array(l, dtype = float) # dype 매개변수에 특정 자료형 float 지정

In [32]:
e

array([1., 2., 3., 4.])

In [33]:
e.dtype

dtype('float64')

In [34]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])

In [35]:
a2.shape # (행, 열)

(2, 3)

In [36]:
a2.ndim

2

In [37]:
a2.dtype

dtype('int64')

In [38]:
a2.dtype

dtype('int64')

In [39]:
a2.itemsize # itemsize = 각 원소 하나의 메모리 크기 (byte)

8

In [40]:
a2.size

6

In [41]:
a2.strides

(24, 8)

→ 행(row) 인덱스가 1 증가할 때는 8바이트 × 3 = 24바이트를 건너뜀

→ 열(column) 인덱스가 1 증가할 때는 8바이트만 이동

In [42]:
a2.flatten()

array([1, 2, 3, 4, 5, 6])

In [43]:
a2.ravel() # 내부 데이터를 그대로 반환하는 뷰

array([1, 2, 3, 4, 5, 6])

### ex3) 넘파이 배열 원소 조회하기

In [44]:
a

array([1, 2, 3, 4])

In [45]:
l

[1, 2, 3, 4]

In [46]:
a[0]

np.int64(1)

In [47]:
l[0]

1

In [48]:
l2 = [[1, 2, 3], [4, 5, 6]]

In [49]:
l2

[[1, 2, 3], [4, 5, 6]]

In [50]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
try:
    l2[0, 1]
except Exception as e:
    print(e)

list indices must be integers or slices, not tuple


In [52]:
l2[0][1]

2

In [53]:
a2[0, 1] # np는 2차원 배열인 경우 인덱스 정보를 튜플로 전달하여 원소를 조회할 수 있다

np.int64(2)

In [54]:
type(a2[0][1])

numpy.int64

In [55]:
a2[0, 1].item()

2

In [56]:
type(a2[0, 1].item())

int

In [57]:
a2[0, 1].real

np.int64(2)

In [58]:
a2[0, 1].imag

np.int64(0)

## 1.3 다차원 배열 클래스의 자료구조

### ex1) 넘파이 모듈의 배열 내부구조 확인

In [59]:
na = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [60]:
na

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [61]:
na.ndim

3

In [62]:
na.shape

(2, 2, 3)

In [63]:
na[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
na[0].shape

(2, 3)

In [65]:
na.__array_interface__

{'data': (1761323406048, False),
 'strides': None,
 'descr': [('', '<i8')],
 'typestr': '<i8',
 'shape': (2, 2, 3),
 'version': 3}

In [66]:
na.strides

(48, 24, 8)

In [67]:
na.__array_interface__['data'][0]

1761323406048

In [68]:
len(na.data.tobytes())

96

In [69]:
na.data.tolist()

[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]

### ex2) data 속성 관리 기준

In [70]:
a = np.array([1, 2, 3, 4])

In [71]:
a

array([1, 2, 3, 4])

In [72]:
a.data

In [73]:
mem = memoryview(a)

In [74]:
mem

In [75]:
a.data[0]

1

In [76]:
a.data.obj

array([1, 2, 3, 4])

In [77]:
a.data.obj[0]

np.int64(1)

In [78]:
a.dtype

dtype('int64')

In [79]:
a.itemsize

8

In [80]:
a.data.hex()

'0100000000000000020000000000000003000000000000000400000000000000'

In [81]:
b = np.array([999, 9999, 99999, 999999])

In [82]:
b.data.hex()[:8]

'e7030000'

In [83]:
hex(999)

'0x3e7'

In [84]:
int('0x3e7', 16)

999

In [85]:
 divmod(999, 16) # 16진수로 표시할 때는 몫과 나머지를 같이 구함

(62, 7)

In [86]:
divmod(62, 16)

(3, 14)

In [87]:
divmod(3, 16)

(0, 3)

In [88]:
a.size

4

In [89]:
for i in range(a.size):
    print(a[i])

1
2
3
4


In [90]:
a.flat # 다차원 배열을 1차원처럼 순회할 수 있게 도와줌

In [91]:
for i in a.flat:
    print(i)

1
2
3
4


In [92]:
c = np.array([1, 2, 3, 4], dtype = float)

In [93]:
c

array([1., 2., 3., 4.])

In [94]:
x = np.frombuffer(c) # frombuffer 복사하지 않고 공유 가능

In [95]:
x

array([1., 2., 3., 4.])

In [96]:
x[0] = 100

In [97]:
x

array([100.,   2.,   3.,   4.])

In [98]:
c

array([100.,   2.,   3.,   4.])

In [99]:
x.dtype

dtype('float64')

In [100]:
x[0]

np.float64(100.0)

In [101]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [102]:
x.base is c

True

In [103]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

## 다차원의 배열의 두 클래스 비교

### ex1) 두 클래스 비교

In [106]:
np.ndarray.__bases__

(object,)

In [109]:
np.matrix.__bases__

(numpy.ndarray,)

In [110]:
l1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [111]:
l1.shape

(8,)

In [113]:
m1 = np.matrix([1, 2, 3, 4, 5, 6, 7, 8])

In [114]:
m1.shape 

(1, 8)

In [115]:
l2 = l1.reshape(2, 4)

In [116]:
l2.shape

(2, 4)

In [117]:
m2 = m1.reshape(2, 4)

In [118]:
m2.shape

(2, 4)

In [119]:
l3 = l2.reshape(2, 2, 2)

In [120]:
try:
    m3 = m2.reshape(2, 2, 2)
except Exception as e:
    print("예외 ", e)

예외  shape too large to be a matrix.


In [122]:
m2_1 = np.asmatrix(l1).reshape(2, 4)

In [123]:
m2_1

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [124]:
l2 * l2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

### ex2) 두 클래스 차이점 확인

In [125]:
nd_ = set(dir(np.ndarray))

In [126]:
md_ = set(dir(np.matrix))

In [127]:
md_ - nd_

{'A',
 'A1',
 'H',
 'I',
 '__annotations__',
 '__dict__',
 '__module__',
 '_align',
 '_collapse',
 'getA',
 'getA1',
 'getH',
 'getI',
 'getT'}

In [130]:
m4 = np.asmatrix('1 2; 3 4')

In [131]:
m4

matrix([[1, 2],
        [3, 4]])

In [132]:
m4.A

array([[1, 2],
       [3, 4]])

In [133]:
m4.getA()

array([[1, 2],
       [3, 4]])

In [134]:
m4.H

matrix([[1, 3],
        [2, 4]])

In [135]:
m4.T

matrix([[1, 3],
        [2, 4]])

In [136]:
from numpy import linalg

In [137]:
linalg.inv(m4)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [138]:
m4.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [139]:
m2

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [140]:
try:
    linalg.inv(m2)
except Exception as e:
    print(e)

Last 2 dimensions of the array must be square


In [141]:
m2.I

matrix([[-5.50000000e-01,  2.50000000e-01],
        [-2.25000000e-01,  1.25000000e-01],
        [ 1.00000000e-01, -2.10437669e-17],
        [ 4.25000000e-01, -1.25000000e-01]])