# 넘파이 모듈의 함수 특징

## 2.1 동일한 이름의 함수와 메소드 지원

### 예제 1 함수와 메소드 처리

In [3]:
import numpy as np

a = np.zeros((5, 5), dtype = np.int_)

In [4]:
a.shape

(5, 5)

In [5]:
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [6]:
a != 0

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [9]:
(a != 0).any() # 여러 개의 불리언 값을 판단해서 하나라도 True가 있으면 True 반환

np.False_

In [8]:
np.any(a != 0)

np.False_

In [10]:
(a != 0).any()

np.False_

In [11]:
np.any

<function any at 0x0000020F7FCC66F0>

In [12]:
np.ndarray.any is np.core.fromnumeric.any

C:\Users\Administrator\AppData\Local\Temp\ipykernel_17236\3956599824.py:1: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.fromnumeric.
  np.ndarray.any is np.core.fromnumeric.any


False

In [13]:
help(np.ndarray.any)

Help on method_descriptor:

any(...) unbound numpy.ndarray method
    a.any(axis=None, out=None, keepdims=False, *, where=True)
    
    Returns True if any of the elements of `a` evaluate to True.
    
    Refer to `numpy.any` for full documentation.
    
    See Also
    --------
    numpy.any : equivalent function



In [15]:
help(a.any)

Help on built-in function any:

any(...) method of numpy.ndarray instance
    a.any(axis=None, out=None, keepdims=False, *, where=True)
    
    Returns True if any of the elements of `a` evaluate to True.
    
    Refer to `numpy.any` for full documentation.
    
    See Also
    --------
    numpy.any : equivalent function



In [16]:
np_ = set(dir(np))

In [17]:
nd_ = set(dir(np.ndarray))

In [18]:
npd_ = np_ & nd_

In [19]:
len(npd_)

48

In [20]:
count = 0
for i in list(npd_):
    count += 1
    print(i, end = " ")
    if count % 5 == 0:
        print()

put any __dir__ shape transpose 
nonzero cumprod argmax conjugate all 
trace round conj prod take 
argmin swapaxes astype argpartition reshape 
var imag mean size diagonal 
cumsum repeat ptp std copy 
ndim sort choose sum argsort 
__doc__ dtype min clip searchsorted 
real partition dot squeeze compress 
max resize ravel 

## 2.2 유니버설 함수 제공

수학의 선형대수를 **벡터와 행렬**을 주로 계산합니다. 
보통 벡터와 행렬의 연산은 구성하는 원소별로(element-wide) 처리합니다.
여러 원소를 가지고 있지만 자동으로 원소별 계산을 처리하는 것을 벡터화 연산이라고 합니다.
**추가적인 순환문을 사용하지 않고도 모든 원소를 계산**한다는 뜻입니다.
이런 연산을 지원하는 특별한 함를 유니버설 함수라고 합니다.

### 예제 1 유니버설 함수 알아보기

In [22]:
a = dir(np)

In [23]:
np.ufunc

numpy.ufunc

In [35]:
type(np.add) # add 함수는 유니버설 

numpy.ufunc

In [34]:
type(np.sort) # sort numpy 내장 함수

numpy._ArrayFunctionDispatcher

In [29]:
set(dir(np.add)) - set(dir(np.sort))

{'_get_strided_loop',
 '_resolve_dtypes_and_context',
 'accumulate',
 'at',
 'identity',
 'nargs',
 'nin',
 'nout',
 'ntypes',
 'outer',
 'reduce',
 'reduceat',
 'resolve_dtypes',
 'signature',
 'types'}

In [30]:
a = np.array([1, 2, 3, 4])

In [31]:
np.add(a, a)

array([2, 4, 6, 8])

In [33]:
np.add.accumulate(a) # 1차원 배열의 원소를 누적한 1차원 배열 반환

array([ 1,  3,  6, 10])

## 예제 2.3 벡터화 연산 이해하기

### 예제 1 벡터화 연산

In [36]:
a = np.arange(6, 10)

In [37]:
a

array([6, 7, 8, 9])

In [38]:
b = np.arange(10, 14)

In [39]:
b

array([10, 11, 12, 13])

In [40]:
c = a * b

In [41]:
c

array([ 60,  77,  96, 117])

In [42]:
d = a[:, np.newaxis]

In [43]:
d

array([[6],
       [7],
       [8],
       [9]])

In [44]:
d.shape

(4, 1)

In [47]:
e = b[np.newaxis, :]

In [48]:
e

array([[10, 11, 12, 13]])

In [49]:
e.shape

(1, 4)

In [50]:
f = d @ e # 행렬곱 => 연산자(@)

In [51]:
f

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [53]:
d.dot(e) # 행렬곱 => dot()

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

## 2.4 축(axis) 계산이 필요한 이유

### 예제1 축에 따른 연산

In [54]:
a2 = np.array([1, 2, 3, 4])

In [55]:
a2

array([1, 2, 3, 4])

In [58]:
a2 = a2.reshape(2, 2) # 축을 추가하이 위해 reshaope 메소드 사용

In [57]:
a2

array([[1, 2],
       [3, 4]])

In [59]:
np.sum(a2)

np.int64(10)

In [60]:
np.sum(a2, axis = 0)

array([4, 6])

In [61]:
np.sum(a2, axis = 1)

array([3, 7])

In [62]:
a3 = np.arange(1, 9)

In [63]:
a3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [65]:
a3 = a3.reshape(2, 2, 2)

In [66]:
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [67]:
a3.shape

(2, 2, 2)

In [68]:
a3[0]

array([[1, 2],
       [3, 4]])

In [69]:
a3[1]

array([[5, 6],
       [7, 8]])

In [70]:
np.sum(a3)

np.int64(36)

In [71]:
np.sum(a3, axis = 0)

array([[ 6,  8],
       [10, 12]])

In [72]:
np.sum(a3, axis = 1)

array([[ 4,  6],
       [12, 14]])

In [73]:
np.sum(a3, axis = 2)

array([[ 3,  7],
       [11, 15]])

## 2.5 계산할 때 원소의 개수 일치하기

수학 선형대수의 벡터와 행렬을 사칙연산을 처리할 때 벡터와 행렬의 원소의 개수가 같아야한다.

이는 동일한 형상 즉 차원을 유지해야 한다는 뜻이다

### 예제 1 원소별로 연산하기

In [74]:
a = np.array([4, 5])

In [75]:
a.shape

(2,)

In [76]:
b = np.array([3, 4, 6])

In [77]:
b.shape

(3,)

In [78]:
try:
    a + b
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (2,) (3,) 


In [79]:
a = np.append(a, [6])

In [80]:
a.shape

(3,)

In [81]:
a + b

array([ 7,  9, 12])

In [82]:
a2 = np.array([[1, 2, 3], [3, 4, 5]])

In [83]:
b2 = np.array([1, 2])

In [84]:
try:
    a2 + b2
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (2,3) (2,) 


In [85]:
b2 = np.append(b2, [3])

In [86]:
b2.shape

(3,)

In [87]:
a2 + b2

array([[2, 4, 6],
       [4, 6, 8]])